# Generated by Django 4.2.13 on 2024-06-06 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StringCalculation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_string', models.CharField(max_length=255)),
                ('max_f_value', models.IntegerField()),
            ],
        ),
    ]
